// src/frontend/src/app/components/plant-selector/plant-selector.component.ts
import { Component, inject, model } from '@angular/core';
import { Plant } from '../../models/plant';
import { PlantService } from '../../services/plant.service';

@Component({
  selector: 'app-plant-selector',
  imports: [],
  templateUrl: './plant-selector.component.html',
})
export class PlantSelectorComponent {
  private plantService = inject(PlantService);

  selectedPlant = model<Plant | null>(null);
  plants = this.plantService.plants;
}

<details class="dropdown">
  <summary class="flex items-center gap-2 border border-gray-300 rounded-md p-2 bg-white w-24 h-24 cursor-pointer">
    <img
      class="h-full w-full overflow-hidden"
      src="{{ selectedPlant()?.imageUrl }}"
      alt="{{ selectedPlant()?.name }}"
    />
  </summary>
  <ul class="menu dropdown-content">
    @for (plant of plants.value(); track $index) {
    <li>
      <a class="bg-white text-black dark:bg-gray-700 dark:text-white" (click)="this.selectedPlant.set(plant)">
        <img class="h-full w-full overflow-hidden" src="{{ plant?.imageUrl }}" alt="{{ plant?.name }}" />
        <span class="text-2xl font-bold">{{ plant?.name }}</span>
      </a>
    </li>
    }
  </ul>
</details>

// src/frontend/src/components/PlantSelector.tsx
"use client";

import { useEffect, useState } from "react";
import { Plant } from "../models/plant";
import { Menu, UnstyledButton } from "@mantine/core";
import usePlants from "../hooks/usePlants";

export type PlantSelectorProps = {
  selectedPlant: Plant | null;
  setSelectedPlant: (plant: Plant) => void;
};

export default function PlantSelector({
  selectedPlant,
  setSelectedPlant,
}: PlantSelectorProps) {
  const { data: plants } = usePlants();
  const [opened, setOpened] = useState(false);

  const plantList = plants.map((p) => (
    <Menu.Item
      key={p.id}
      value={p.id}
      className="flex items-center gap-2 w-14"
      onClick={() => {
        setSelectedPlant(p);
        setOpened(false);
      }}
    >
      <img className="w-8 h-8" src={p.imageUrl} alt={p.name} />
      <span>{p.name}</span>
    </Menu.Item>
  ));

  return (
    <Menu
      onOpen={() => setOpened(true)}
      onClose={() => setOpened(false)}
      radius="md"
      width="target"
      withinPortal
    >
      <Menu.Target>
        <UnstyledButton data-expanded={opened || undefined}>
          <div className="flex items-center gap-2 border border-gray-300 rounded-md p-2 bg-white w-24 h-24 ">
            <img
              className="h-full w-full overflow-hidden"
              src={selectedPlant?.imageUrl}
              alt={selectedPlant?.name}
            />
          </div>
        </UnstyledButton>
      </Menu.Target>
      <Menu.Dropdown>{plantList}</Menu.Dropdown>
    </Menu>
  );
}
